config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  get 'posts/:user_id/new'=> 'posts#new',as: 'posts_new'
  post 'posts/:user_id/create'=> 'posts#create',as: 'p_create'
  get  'posts/:user_id/edit'=> 'posts#edit',as: 'post_edit'
  patch 'posts/:user_id/update'=>'posts#update',as: 'post_update'
  delete 'posts/:user_id/destroy'=> 'posts#destroy',as: 'post_destroy'
  get 'users/new'=>'users#new',as: 'users_new'
  post 'users/create'=>'users#create',as: 'users_create'
  get 'users/:user_id/edit'=>'users#edit',as: 'users_edit'
  patch 'users/:user_id/update'=>'users#update',as: 'users_update'
  get 'users/:user_id'=>'users#show',as: 'users_show'
  get 'sessions/new'=>'sessions#new',as: 'sessions_new'
  post 'sessions/create'=>'sessions#create',as: 'sessions_create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user,class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   include SessionsHelper
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def top
     @posts=Post.all
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
   def create
    @like = current_user.likes.create(post_id: params[:post_id])
    redirect_back(fallback_location: root_path)
   end

  def destroy
    @post = Post.find(params[:post_id])
    @like = current_user.likes.find_by(post_id: @post.id)
    @like.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new 
    @post = Post.new
  end
  def create
    user=User.find_by(id: session[:user_id])
    @post=user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to users_show_path
    else
      render :new
    end  
  end

  def edit
    @post=Post.find_by(id: params[:user_id])
  end
  def update
       @post=Post.find_by(id: params[:user_id])
     if @post.update(post_params)
        flash[:notice]="プランナー情報を更新しました。"
        redirect_to users_show_path(@post.id) 
     else
        render :edit
     end
  end
  def destroy
    @post=Post.find_by(id: params[:user_id]).destroy
      redirect_to users_show_path(@post.id) 
  end
  private
    def post_params
       params.require(:post).permit(:title,:content,:user_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end
    def create
        @user = User.find_by(email: params[:session][:email].downcase)
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id]=@user.id
             redirect_to users_show_path(@user.id)
        else
            redirect_to root_url
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user=User.new
  end
  def create
    @user=User.new(user_params)
    if @user.save
      session[:user_id]=@user.id
       redirect_to root_path
       flash[:email] = "Your message was successfully sent."
    else
        flash.now[:error] = 'Invalid email/password combination'
         render 'new'
    end
  end
  def show
    @user = User.find_by(id: params[:user_id])
    @posts =@user.posts.all
  end
  def edit
       @user = User.find_by(id: params[:user_id])
  end

  def update 
      @user = User.find_by(id: params[:user_id])
     if @user.update(user_params)
       flash[:success] = "Profile updated"
       redirect_to users_show_path(@user.id)
     else
        render :edit
     end
  end
  def destroy
    @user=User.find_by(id: params[:user_id]).destroy
      redirect_to root_path
  end

    private
    def user_params
       params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?(user)
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
Top!!
<p>全体<%=@posts.count%>件のポストが投稿</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if User.find_by(id: session[:user_id]).present? %>
      <%= link_to "mypage",users_show_path(User.find_by(id: session[:user_id]).id) %>
      <%= link_to "post",posts_new_path(User.find_by(id: session[:user_id]).id) %>
      <%= link_to "top",root_path%>
    <% else %>
      <%= link_to "sign up",users_new_path %>
      <%= link_to "log_in",sessions_new_path %>
    <% end %>>    
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>
<p>Find me in app/views/posts/edit.html.erb</p>
<%= form_for @post, url: post_update_path(@post.id) do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %></br>
 <%= f.label :content%>
 <%= f.text_field :content, class: "class_name", maxlength: 40 %></br>
 <%= f.submit "click "%>
<% end %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

<%= form_for @post,url: p_create_path do |f| %>
 <%= f.label :title %>
 <%= f.text_field :title %></br>
 <%= f.label :content%>
 <%= f.text_field :content, class: "class_name", maxlength: 40 %></br>
 <%= f.submit "click "%>
<% end %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_with model: @user ,url: users_update_path(@user.id), local: true  do |f| %>
     
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
        <%= f.submit "click" %>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user,url: users_create_path do |f| %>
<%= f.label :name %>
 <%= f.text_field :name %></br>
<%= f.label :email%>
 <%= f.text_field :email, class: "class_name", maxlength: 40 %></br>
 <%= f.label :password%>
 <%= f.password_field :password, class: "class_name", maxlength: 40 %></br>
  <%= f.label :password_confirmation%>
 <%= f.password_field :password_confirmation, class: "class_name", maxlength: 40 %></br>
<%= f.submit "click "%>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= User.find_by(id: params[:user_id]).name %>
<%= User.find_by(id: params[:user_id]).email %>
<%= @user.name %>
<%=link_to "edit",users_edit_path%>
<% @posts.each do |post| %>
<p><%= post.title%></p>
<p><%= post.content%></p>
<%=link_to "post_edit",post_edit_path(post.id) %>
<%= link_to "post_destroy",post_destroy_path(post.id), method: :delete %>
<% end %>
        
 